$text_user_account_on_login_page = ".//*[@id='branding']/h1"
$uname_on_login_page = 'edit-name'
$passwd_on_login_page = 'edit-pass'
$login_button = 'edit-submit'
$select_type_as_program = ".//*[@id='edit-type']/option[3]"
$input_field_name = 'edit-title'
$published_dropdown_list = 'edit-published'
$apply_button = 'edit-submit-view-all-content'
$pecker_prog_displayed = ".//*[@id='block-system-main']/div/div/div[3]/table/tbody/tr[1]/td[1]"
$pecker_prog_link = ".//*[@id='block-system-main']/div/div/div[3]/table/tbody/tr/td[1]/a"
$sort_by_type = ".//*[@id='block-system-main']/div/div/div[3]/table/thead/tr/th[3]/a"
$rotten_tomatoes_tab = ".//*[@id='branding']/ul/li[3]/a"
$imdb_id_field_on_rotten_tomatoes_tab = 'edit-field-imdb-id-und-0-value--2'
$update_rotten_tomatoes_data_button = 'edit-submit--2'
$rotten_tomato_movie_title = ".//*[@id='programme-node-form--2']/div/div/div[1]/div/div/div/h2"
$content_menu = ".//*[@id='admin-menu-menu']/li[1]/a"
$filter_by_rotten_tomato_movie = 'edit-type'
$rotten_tomato_movie_list_displayed = ".//*[@id='edit-filters']/div/div/div[1]/ul/li/em[2]"
$imdb_id_property_for_new_node = ".//*[@id='node-5922']/div/div[12]/div[1]"
$abridged_cast_property_for_new_node = ".//*[@id='node-5922']/div/div[14]/div[1]"
$abridged_directors_property_for_new_node = ".//*[@id='node-5922']/div/div[15]/div[1]"
$genres_property_for_new_node = ".//*[@id='node-5922']/div/div[3]/div[1]"
$synopsis_property_for_new_node = ".//*[@id='node-5922']/div/div[11]/div[1]"
$logout_button = ".//*[@id='admin-menu-account']/li[1]/a"
